server:
  port: 10301
spring:
  application:
    name: feign-eureka-client

##eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://lmy1:10001/eureka/,http://lmy2:10002/eureka/,http://lmy3:10003/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    # 设置微服务调用地址为IP优先（缺省为false）
    prefer-ip-address: true
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 30
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 90

#feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
