server:
  port: 10103
spring:
  application:
    name: eureka-client
  boot:
      admin:
        client:
          url: http://127.0.0.1:10401

cluster:
  client-name: client3

##eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://lmy3:10003/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    # 设置微服务调用地址为IP优先（缺省为false）
    prefer-ip-address: true
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 30
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: ALWAYS


