
spring:
  profiles:
    active: server1
#    active: server2
#    active: server3

#server.port=10001
#cluster.eureka.server1=localhost
#cluster.eureka.port1=10001

#server.port=10002
#cluster.eureka.server2=localhost
#cluster.eureka.port2=10002

#server.port=10003
#cluster.eureka.server3=localhost
#cluster.eureka.port3=10003

#https://blog.csdn.net/weixin_43650254/article/details/95075098
